package com.innowise.entity;

import com.innowise.dto.UserDto;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * The Registration class is a simple Java class that represents a user registration. It contains the username, password
 * and authority ID of the user being registered.
 * This class uses the Lombok annotations @Data, @NoArgsConstructor, @AllArgsConstructor, and @Builder to generate
 * constructors, getter/setter methods, and the toDto method that creates a UserDto instance based on the fields
 * of this class.
 * The fields of this class are accessed and modified using the getter/setter methods generated by the @Data annotation.
 * The toDto method creates a UserDto instance and sets its fields using the values of the fields in this class.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Registration {

    /**
     * The username of the user being registered.
     */
    private String username;
    /**
     * The password of the user being registered.
     */
    private String password;
    /**
     * The ID of the authority of the user being registered.
     */
    private Long authorityId;

    /**
     * Converts this registration to a UserDto instance.
     *
     * @return a UserDto instance representing this registration
     */
    public UserDto toDto() {
        UserDto dto = new UserDto();
        dto.setUsername(username);
        dto.setPassword(password);
        dto.setAuthorityId(authorityId);
        return dto;
    }
}
